name: release

on:
  push:
    tags:
      - v*.*.*
    branches-ignore:
      - '**'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }} 

jobs:
  build-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.3.2f1 
          targetPlatform: WebGL

      # Deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/WebGL/WebGL
